name: blocks_app
description: blocks test

version: 1.1.10+20

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^3.1.1
  orientation: ^1.2.0
  path_provider: ^1.6.18
  webview_flutter: ^1.0.7
  archive: ^2.0.13
  package_info: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
